name: Node.js Package

# 触发工作流程的事件
on:
  push:
    branches:
      - main

# 按顺序运行作业
jobs:
  publish-gpr:
    # 指定的运行器环境
    runs-on: ubuntu-latest
    # 设置 node 版本
    strategy:
      matrix:
        node-version: [14]
    steps:
      # 拉取 github 仓库代码
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 获取完整历史，这样 Git 标签和提交历史都会存在
      # 设定 node 环境
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # 默认配置
          registry-url: https://registry.npmjs.org/
      # 安装依赖，相当于 npm ci
      - name: Install dependencies
        run: npm install
      # 执行构建步骤
      - name: 构建
        run: |
          npm run build
      # 设置git用户
      - name: Set Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
       # 新增 GitHub Pages 部署步骤
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./dist  # 指向构建后的静态文件目录
          keep_files: true      # 保留已有文件
      # 更改版本号
      - name: 更改版本号
        run: |
          npm run release
      - name: Commit version bump
        run: |
          git add . 
          git commit -m "chore: bump version [skip ci]" || echo "No changes to commit"
          git push

