name: CI
on:
  push:
    branches:
      # 触发ci/cd的代码分支
      - main
jobs:
  build:
    # 指定操作系统
    runs-on: ubuntu-latest
    steps:
      # 将代码拉到虚拟机
      - name: Checkout repository
        uses: actions/checkout@v2
      # 指定node版本
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      # 依赖缓存策略
      - name: Cache
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}
      # 依赖下载
      - name: Installing Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm install
      # 4. 自动升级 patch 版本号
      - name: Bump version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          npm version patch -m "chore(release): bump version to %s"
          git push origin HEAD
          git push origin --tags
      # 打包
      - name: Running Build
        run: npm run build
      # 发布
      - name: Running Publish
        run: npm publish
        env:
          # NPM_TOKEN is access token
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
